nelmio_api_doc:
    documentation:
        info:
            title: Bilemo Doc
            description: BileMo est une entreprise offrant toute une sélection de téléphones mobiles haut de gamme.
            version: '1.2'
        paths:
            /api/auth/signup:
                post:
                    tags:
                        - Reseller
                    summary: Permet de créer un Reseller.
            /api/auth/login:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Authentification
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '401':
                            description: Identifiants erronés
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/InvalidCredentials'
                        '400':
                            description: Mauvaise requête
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/BadRequest'
            /api/token/refresh:
                post:
                    tags:
                        - Authentification
                    summary: Permet de rafraichir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/RefreshCredentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/InvalidCredentials'

        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                        refresh_token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        email:
                            type: string
                            default: admin@bilemo.com
                        password:
                            type: string
                            default: password
                RefreshCredentials:
                    type: object
                    properties:
                        refresh_token:
                            type: string
                            default: 53580accb39d2960fb06aa61676224ea24470b1732dec198d9d39bc7022ae53b01aaeb5d249fb4eb5b46fc4efaa672560aa2a9c79767e354582f87efc010b3c2
                InvalidCredentials:
                    type: object
                    properties:
                        code:
                            type: int
                            readOnly: true
                        message:
                            type: string
                            readOnly: true
                BadRequest:
                    type: object
                    properties:
                        code:
                            type: int
                            readOnly: true
                        message:
                            type: string
                            readOnly: true
                UnprocessableEntity:
                    type: object
                    properties:
                        code:
                            type: int
                            readOnly: true
                        message:
                            type: string
                            readOnly: true
                NotFound:
                    type: object
                    properties:
                        message:
                            type: string
                            readOnly: true
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization
        security:
            - bearerAuth: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
